### HackerEarth Machine Learning Challenge: How to not Lose Customer in 10 Days

Link: https://www.hackerearth.com/challenges/competitive/hackerearth-machine-learning-challenge-predict-customer-churn/

**Problem Statement**: No business can thrive without it’s customers. On the flip side, customers leaving the business is a nightmare that every business owner dreads!

In fact, one of the key metrics to measure a business’ success is by measuring its customer churn rate - the lower the churn, the more loved the company is. 

Typically, every user of a product or a service is assigned a prediction value that estimates their state of churn at any given time. This value may be based on multiple factors such as the user’s demographic, their browsing behavior and historical purchase data, among other details.

This value factors in unique and proprietary predictions of how long a user will remain a customer and is updated every day for all users who have purchased at least one of the products/services. The values assigned are between 1 and 5.

**Task**: An up-and-coming startup is keen on reducing its customer churn and has hired you as a Machine Learning engineer for this task. As an expert, you are required to build a sophisticated Machine Learning model that predicts the churn score for a website based on multiple features.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/dataset/train.csv")

In [ ]:
dataset.head()

customer_id  ... churn_risk_score
0      fffe4300490044003600300030003800  ...                2
1  fffe43004900440032003100300035003700  ...                1
2      fffe4300490044003100390032003600  ...                5
3  fffe43004900440036003000330031003600  ...                5
4  fffe43004900440031003900350030003600  ...                5

[5 rows x 25 columns]

In [ ]:
len(dataset)

36992

In [ ]:
dataset.shape

(36992, 25)

In [ ]:
dataset.describe()

age  days_since_last_login  ...  points_in_wallet  churn_risk_score
count  36992.000000           36992.000000  ...      33549.000000      36992.000000
mean      37.118161             -41.915576  ...        686.882199          3.463397
std       15.867412             228.819900  ...        194.063624          1.409661
min       10.000000            -999.000000  ...       -760.661236         -1.000000
25%       23.000000               8.000000  ...        616.150000          3.000000
50%       37.000000              12.000000  ...        697.620000          4.000000
75%       51.000000              16.000000  ...        763.950000          5.000000
max       64.000000              26.000000  ...       2069.069761          5.000000

[8 rows x 6 columns]

In [ ]:
dataset.churn_risk_score.value_counts()

 3    10424
 4    10185
 5     9827
 2     2741
 1     2652
-1     1163
Name: churn_risk_score, dtype: int64

**Data Cleaning**

In [ ]:
# Find the Null Values
dataset.isnull().sum()

customer_id                        0
Name                               0
age                                0
gender                             0
security_no                        0
region_category                 5428
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types            288
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                3443
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
churn_risk_score                   0
dtype: int64

In [ ]:
dataset.shape

(36992, 25)

In [ ]:
# Fill the NA values rather than dropping it
for i in dataset.columns:
    if dataset[i].dtype=='float64':
        dataset[i]=dataset[i].fillna(dataset[i].mean())
    else:
        dataset[i]=dataset[i].fillna(method='ffill')

In [ ]:
dataset.shape

(36992, 25)

In [ ]:
dataset.isnull().sum()

customer_id                     0
Name                            0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             0
internet_option                 0
last_visit_time                 0
days_since_last_login           0
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
used_special_discount           0
offer_application_preference    0
past_complaint                  0
complaint_status                0
feedback                        0
churn_risk_score                0
dtype: int64

In [ ]:
# Dropping the unimportant features of table
dataset.head()

customer_id  ... churn_risk_score
0      fffe4300490044003600300030003800  ...                2
1  fffe43004900440032003100300035003700  ...                1
2      fffe4300490044003100390032003600  ...                5
3  fffe43004900440036003000330031003600  ...                5
4  fffe43004900440031003900350030003600  ...                5

[5 rows x 25 columns]

In [ ]:
def columnGetter():
  column_names = []
  for cols in dataset.columns:
    column_names.append(cols)
  return column_names

In [ ]:
cols_name = columnGetter()

In [ ]:
for i in range(0,len(cols_name)):
  print(cols_name[i])

customer_id
Name
age
gender
security_no
region_category
membership_category
joining_date
joined_through_referral
referral_id
preferred_offer_types
medium_of_operation
internet_option
last_visit_time
days_since_last_login
avg_time_spent
avg_transaction_value
avg_frequency_login_days
points_in_wallet
used_special_discount
offer_application_preference
past_complaint
complaint_status
feedback
churn_risk_score


### Features Selections and Dropping Other Features

In [ ]:
dataset.head()

customer_id  ... churn_risk_score
0      fffe4300490044003600300030003800  ...                2
1  fffe43004900440032003100300035003700  ...                1
2      fffe4300490044003100390032003600  ...                5
3  fffe43004900440036003000330031003600  ...                5
4  fffe43004900440031003900350030003600  ...                5

[5 rows x 25 columns]

In [ ]:
dataset = dataset.drop(["customer_id","Name","security_no","referral_id","last_visit_time"],axis=1)

In [ ]:
dataset.head()

age gender  ...                  feedback churn_risk_score
0   18      F  ...  Products always in Stock                2
1   32      F  ...     Quality Customer Care                1
2   44      F  ...              Poor Website                5
3   37      M  ...              Poor Website                5
4   31      F  ...              Poor Website                5

[5 rows x 20 columns]

In [ ]:
dataset.isnull().sum()

age                             0
gender                          0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
preferred_offer_types           0
medium_of_operation             0
internet_option                 0
days_since_last_login           0
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
used_special_discount           0
offer_application_preference    0
past_complaint                  0
complaint_status                0
feedback                        0
churn_risk_score                0
dtype: int64

In [ ]:
dataset.shape

(36992, 20)

#### Gender

In [ ]:
dataset.gender.unique()

array(['F', 'M', 'Unknown'], dtype=object)

In [ ]:
dataset.gender.value_counts()

F          18490
M          18443
Unknown       59
Name: gender, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
dataset.head()

age gender  ...                  feedback churn_risk_score
0   18      F  ...  Products always in Stock                2
1   32      F  ...     Quality Customer Care                1
2   44      F  ...              Poor Website                5
3   37      M  ...              Poor Website                5
4   31      F  ...              Poor Website                5

[5 rows x 20 columns]

In [ ]:
dataset["gender"] = le.fit_transform(dataset.gender)

In [ ]:
dataset["gender"]

0        0
1        0
2        0
3        1
4        0
        ..
36987    0
36988    0
36989    0
36990    1
36991    1
Name: gender, Length: 36992, dtype: int64

In [ ]:
dataset.head()

age  gender  ...                  feedback churn_risk_score
0   18       0  ...  Products always in Stock                2
1   32       0  ...     Quality Customer Care                1
2   44       0  ...              Poor Website                5
3   37       1  ...              Poor Website                5
4   31       0  ...              Poor Website                5

[5 rows x 20 columns]

#### Region_Category

In [ ]:
dataset.region_category.unique()

array(['Village', 'City', 'Town'], dtype=object)

In [ ]:
dataset["region_category"] = le.fit_transform(dataset.region_category)

In [ ]:
dataset.head(20)

age  gender  ...                  feedback churn_risk_score
0    18       0  ...  Products always in Stock                2
1    32       0  ...     Quality Customer Care                1
2    44       0  ...              Poor Website                5
3    37       1  ...              Poor Website                5
4    31       0  ...              Poor Website                5
5    13       1  ...       No reason specified                3
6    21       1  ...       No reason specified                3
7    42       1  ...      Poor Product Quality                5
8    44       1  ...     Poor Customer Service                3
9    45       0  ...     Poor Customer Service                4
10   25       0  ...      Poor Product Quality                5
11   60       1  ...              Too many ads                3
12   11       1  ...     Poor Customer Service                4
13   34       1  ...      Poor Product Quality                4
14   40       1  ...              Poor Website                3
15   16       0  ...              Too many ads                5
16   57       0  ...              Too many ads                5
17   11       1  ...     Poor Customer Service                3
18   39       1  ...       No reason specified                5
19   45       1  ...  Products always in Stock                2

[20 rows x 20 columns]

#### Membership Category

In [ ]:
dataset["membership_category"].value_counts()

Basic Membership       7724
No Membership          7692
Gold Membership        6795
Silver Membership      5988
Premium Membership     4455
Platinum Membership    4338
Name: membership_category, dtype: int64

In [ ]:
dataset.membership_category.unique()

array(['Platinum Membership', 'Premium Membership', 'No Membership',
       'Gold Membership', 'Silver Membership', 'Basic Membership'],
      dtype=object)

In [ ]:
dataset["membership_category"] = le.fit_transform(dataset.membership_category)

In [ ]:
dataset.head()

age  gender  ...                  feedback  churn_risk_score
0   18       0  ...  Products always in Stock                 2
1   32       0  ...     Quality Customer Care                 1
2   44       0  ...              Poor Website                 5
3   37       1  ...              Poor Website                 5
4   31       0  ...              Poor Website                 5

[5 rows x 20 columns]

In [ ]:
dataset["membership_category"].value_counts()

0    7724
2    7692
1    6795
5    5988
4    4455
3    4338
Name: membership_category, dtype: int64

#### Joining Date

In [ ]:
dataset["joining_date"].value_counts()

02-06-2015    55
04-07-2015    51
21-06-2015    50
03-08-2016    49
26-06-2015    49
              ..
16-03-2016    19
03-06-2016    18
12-09-2015    18
03-07-2017    18
04-03-2015    16
Name: joining_date, Length: 1096, dtype: int64

In [ ]:
dataset["joining_date"].unique()

array(['17-08-2017', '28-08-2017', '11-11-2016', ..., '11-12-2017',
       '25-09-2016', '15-04-2017'], dtype=object)

In [ ]:
#df = df.replace('-', '', regex=True).astype(int)
dataset["joining_date"] = dataset["joining_date"].replace("-",'',regex=True).astype(int)

In [ ]:
dataset.head()

age  gender  ...                  feedback  churn_risk_score
0   18       0  ...  Products always in Stock                 2
1   32       0  ...     Quality Customer Care                 1
2   44       0  ...              Poor Website                 5
3   37       1  ...              Poor Website                 5
4   31       0  ...              Poor Website                 5

[5 rows x 20 columns]

#### Joined Through Referral

In [ ]:
dataset["joined_through_referral"].value_counts()

No     15839
Yes    15715
?       5438
Name: joined_through_referral, dtype: int64

In [ ]:
dataset = dataset[dataset["joined_through_referral"]!="?"]

In [ ]:
dataset["joined_through_referral"].value_counts()

No     15839
Yes    15715
Name: joined_through_referral, dtype: int64

In [ ]:
dataset["joined_through_referral"] = le.fit_transform(dataset["joined_through_referral"])

In [ ]:
dataset.shape

(31554, 20)

In [ ]:
dataset["joined_through_referral"].value_counts()

0    15839
1    15715
Name: joined_through_referral, dtype: int64

#### Preferred Offer Types

In [ ]:
dataset.head()

age  gender  ...                  feedback  churn_risk_score
0   18       0  ...  Products always in Stock                 2
2   44       0  ...              Poor Website                 5
3   37       1  ...              Poor Website                 5
4   31       0  ...              Poor Website                 5
5   13       1  ...       No reason specified                 3

[5 rows x 20 columns]

In [ ]:
dataset["preferred_offer_types"].unique()

array(['Gift Vouchers/Coupons', 'Credit/Debit Card Offers',
       'Without Offers'], dtype=object)

In [ ]:
dataset["preferred_offer_types"].value_counts()

Gift Vouchers/Coupons       10617
Credit/Debit Card Offers    10554
Without Offers              10383
Name: preferred_offer_types, dtype: int64

In [ ]:
dataset["preferred_offer_types"] = le.fit_transform(dataset["preferred_offer_types"])

In [ ]:
dataset.head()

age  gender  ...                  feedback  churn_risk_score
0   18       0  ...  Products always in Stock                 2
2   44       0  ...              Poor Website                 5
3   37       1  ...              Poor Website                 5
4   31       0  ...              Poor Website                 5
5   13       1  ...       No reason specified                 3

[5 rows x 20 columns]

#### Medium of Operation

In [ ]:
dataset["medium_of_operation"].unique()

array(['?', 'Desktop', 'Smartphone', 'Both'], dtype=object)

In [ ]:
dataset = dataset[dataset["medium_of_operation"]!="?"]

In [ ]:
dataset["medium_of_operation"].unique()

array(['Desktop', 'Smartphone', 'Both'], dtype=object)

In [ ]:
dataset["medium_of_operation"].value_counts()

Desktop       11903
Smartphone    11802
Both           3258
Name: medium_of_operation, dtype: int64

In [ ]:
dataset["medium_of_operation"] = le.fit_transform(dataset["medium_of_operation"])

In [ ]:
dataset["medium_of_operation"].unique()

array([1, 2, 0])

In [ ]:
dataset["medium_of_operation"].value_counts()

1    11903
2    11802
0     3258
Name: medium_of_operation, dtype: int64

#### Internet

In [ ]:
dataset.head()

age  gender  ...               feedback  churn_risk_score
2   44       0  ...           Poor Website                 5
3   37       1  ...           Poor Website                 5
4   31       0  ...           Poor Website                 5
6   21       1  ...    No reason specified                 3
8   44       1  ...  Poor Customer Service                 3

[5 rows x 20 columns]

In [ ]:
dataset["internet_option"].unique()

array(['Wi-Fi', 'Mobile_Data', 'Fiber_Optic'], dtype=object)

In [ ]:
dataset["internet_option"] = le.fit_transform(dataset["internet_option"])

In [ ]:
dataset["internet_option"].unique()

array([2, 1, 0])

In [ ]:
dataset["internet_option"].value_counts()

1    9012
2    9010
0    8941
Name: internet_option, dtype: int64

#### Used Special Discount

In [ ]:
dataset["used_special_discount"].value_counts()

Yes    14840
No     12123
Name: used_special_discount, dtype: int64

In [ ]:
dataset["used_special_discount"] = le.fit_transform(dataset["used_special_discount"])

In [ ]:
dataset["used_special_discount"].value_counts()

1    14840
0    12123
Name: used_special_discount, dtype: int64

In [ ]:
dataset.head()

age  gender  ...               feedback  churn_risk_score
2   44       0  ...           Poor Website                 5
3   37       1  ...           Poor Website                 5
4   31       0  ...           Poor Website                 5
6   21       1  ...    No reason specified                 3
8   44       1  ...  Poor Customer Service                 3

[5 rows x 20 columns]

#### Offer Application Preference

In [ ]:
dataset["offer_application_preference"].value_counts()

Yes    14829
No     12134
Name: offer_application_preference, dtype: int64

In [ ]:
dataset["offer_application_preference"] = le.fit_transform(dataset["offer_application_preference"])

In [ ]:
dataset["offer_application_preference"].value_counts()

1    14829
0    12134
Name: offer_application_preference, dtype: int64

#### Past Complaint

In [ ]:
dataset["past_complaint"].value_counts()

No     13528
Yes    13435
Name: past_complaint, dtype: int64

In [ ]:
dataset["past_complaint"] = le.fit_transform(dataset["past_complaint"])

In [ ]:
dataset["past_complaint"].value_counts()

0    13528
1    13435
Name: past_complaint, dtype: int64

#### Complaint Status

In [ ]:
dataset["complaint_status"].value_counts()

Not Applicable              13528
Unsolved                     3416
Solved                       3397
Solved in Follow-up          3330
No Information Available     3292
Name: complaint_status, dtype: int64

In [ ]:
dataset["complaint_status"] = le.fit_transform(dataset["complaint_status"])

In [ ]:
dataset["complaint_status"].value_counts()

1    13528
4     3416
2     3397
3     3330
0     3292
Name: complaint_status, dtype: int64

In [ ]:
dataset.head()

age  gender  ...               feedback  churn_risk_score
2   44       0  ...           Poor Website                 5
3   37       1  ...           Poor Website                 5
4   31       0  ...           Poor Website                 5
6   21       1  ...    No reason specified                 3
8   44       1  ...  Poor Customer Service                 3

[5 rows x 20 columns]

#### Feedback

In [ ]:
dataset["feedback"].unique()

array(['Poor Website', 'No reason specified', 'Poor Customer Service',
       'Poor Product Quality', 'Too many ads', 'User Friendly Website',
       'Quality Customer Care', 'Products always in Stock',
       'Reasonable Price'], dtype=object)

In [ ]:
dataset["feedback"] = le.fit_transform(dataset["feedback"])

In [ ]:
dataset.head()

age  gender  region_category  ...  complaint_status  feedback  churn_risk_score
2   44       0                1  ...                 3         3                 5
3   37       1                0  ...                 4         3                 5
4   31       0                0  ...                 2         3                 5
6   21       1                1  ...                 3         0                 3
8   44       1                2  ...                 3         1                 3

[5 rows x 20 columns]

#### Churn Risk Score

In [ ]:
dataset["churn_risk_score"].value_counts()

 3    7608
 4    7365
 5    7136
 2    2027
 1    1950
-1     877
Name: churn_risk_score, dtype: int64

In [ ]:
dataset.shape

(26963, 20)

### Outlier Detection and Removal for numeric values

#### Days Since Last Login

In [ ]:
dataset.head()

age  gender  region_category  ...  complaint_status  feedback  churn_risk_score
2   44       0                1  ...                 3         3                 5
3   37       1                0  ...                 4         3                 5
4   31       0                0  ...                 2         3                 5
6   21       1                1  ...                 3         0                 3
8   44       1                2  ...                 3         1                 3

[5 rows x 20 columns]

In [ ]:
dataset["days_since_last_login"].value_counts()

 12     1738
 13     1721
 14     1680
 11     1675
 15     1634
 16     1520
 10     1503
-999    1458
 9      1361
 17     1270
 8      1151
 18     1061
 7      1040
 19      997
 6       922
 5       881
 20      840
 21      730
 4       719
 22      672
 3       615
 23      535
 2       447
 24      355
 1       232
 25      145
 26       61
Name: days_since_last_login, dtype: int64

In [ ]:
# Its seen that day_since_last_login can't be negative so remove those values
dataset = dataset[dataset["days_since_last_login"]!=-999]

In [ ]:
dataset["days_since_last_login"].value_counts()

12    1738
13    1721
14    1680
11    1675
15    1634
16    1520
10    1503
9     1361
17    1270
8     1151
18    1061
7     1040
19     997
6      922
5      881
20     840
21     730
4      719
22     672
3      615
23     535
2      447
24     355
1      232
25     145
26      61
Name: days_since_last_login, dtype: int64

In [ ]:
dataset.shape

(25505, 20)

In [ ]:
dataset.head()

age  gender  region_category  ...  complaint_status  feedback  churn_risk_score
2   44       0                1  ...                 3         3                 5
3   37       1                0  ...                 4         3                 5
4   31       0                0  ...                 2         3                 5
6   21       1                1  ...                 3         0                 3
8   44       1                2  ...                 3         1                 3

[5 rows x 20 columns]

#### Average Time Spend

In [ ]:
dataset["avg_time_spent"].value_counts()

 34.100000     17
 32.960000     15
 30.560000     14
 33.280000     13
 33.680000     13
               ..
 784.030000     1
 377.050000     1
-886.577661     1
 54.880000      1
 240.040000     1
Name: avg_time_spent, Length: 19308, dtype: int64

In [ ]:
# Again Average Spent Time can't be negative
dataset = dataset[dataset["avg_time_spent"]>=0]

In [ ]:
dataset.shape

(24330, 20)

#### Average Transaction Value

In [ ]:
print(dataset["avg_transaction_value"].value_counts())

4407.26     2
38138.54    2
61756.98    2
33922.27    2
48440.34    2
           ..
32065.13    1
17721.03    1
25072.82    1
41869.33    1
35302.32    1
Name: avg_transaction_value, Length: 24283, dtype: int64


In [ ]:
dataset.head()

age  gender  region_category  ...  complaint_status  feedback  churn_risk_score
2   44       0                1  ...                 3         3                 5
3   37       1                0  ...                 4         3                 5
4   31       0                0  ...                 2         3                 5
6   21       1                1  ...                 3         0                 3
8   44       1                2  ...                 3         1                 3

[5 rows x 20 columns]

#### Average Frequency Login Days

In [ ]:
dataset["avg_frequency_login_days"].value_counts()

Error           2308
13               928
17               899
14               891
6                887
                ... 
-14.86449559       1
17.65581603        1
-10.05103279       1
49.46164518        1
-5.585924221       1
Name: avg_frequency_login_days, Length: 1103, dtype: int64

In [ ]:
# Remove the Error Keyword which is not suitable for numerical value
dataset = dataset[dataset["avg_frequency_login_days"]!="Error"]

In [ ]:
dataset["avg_frequency_login_days"] = pd.to_numeric(dataset["avg_frequency_login_days"])

In [ ]:
dataset.shape

(22022, 20)

#### Points in Wallet

In [ ]:
dataset["points_in_wallet"].unique()

array([500.69     , 567.66     , 663.06     , ..., 242.9796255,
       725.89     , 197.2644136])

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22022 entries, 2 to 36990
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   age                           22022 non-null  int64  
 1   gender                        22022 non-null  int64  
 2   region_category               22022 non-null  int64  
 3   membership_category           22022 non-null  int64  
 4   joining_date                  22022 non-null  int64  
 5   joined_through_referral       22022 non-null  int64  
 6   preferred_offer_types         22022 non-null  int64  
 7   medium_of_operation           22022 non-null  int64  
 8   internet_option               22022 non-null  int64  
 9   days_since_last_login         22022 non-null  int64  
 10  avg_time_spent                22022 non-null  float64
 11  avg_transaction_value         22022 non-null  float64
 12  avg_frequency_login_days      22022 non-null  float64
 13  p

### Machine Learning Implementation

#### Logisitic Regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
X = dataset.drop(["churn_risk_score"],axis=1)
y = dataset["churn_risk_score"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [ ]:
modelLR = LogisticRegression(max_iter=10000)

modelLR.fit(X_train,y_train)

y_pred = modelLR.predict(X_test)

In [ ]:
# Accuracy Score
modelLR.score(X_test,y_test)

0.2606129398410897

In [ ]:
# Classification Report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       140
           1       0.13      0.12      0.13       312
           2       0.14      0.16      0.15       344
           3       0.28      0.61      0.39      1254
           4       0.30      0.11      0.16      1218
           5       0.28      0.13      0.18      1137

    accuracy                           0.26      4405
   macro avg       0.19      0.19      0.17      4405
weighted avg       0.26      0.26      0.22      4405



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[  0   7  10  88  15  20]
 [  0  39  44 196  12  21]
 [  0  42  55 208  21  18]
 [  0  76 109 770 141 158]
 [  0  65  76 773 137 167]
 [  0  64  93 708 125 147]]


#### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
modelRF = RandomForestClassifier()

modelRF.fit(X_train,y_train)

y_pred = modelRF.predict(X_test)

In [ ]:
# Accurracy Score
modelRF.score(X_test,y_test)

0.7377979568671964

In [ ]:
# Classification Report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       140
           1       0.69      0.74      0.71       312
           2       0.74      0.72      0.73       344
           3       0.89      0.89      0.89      1254
           4       0.66      0.60      0.63      1218
           5       0.67      0.81      0.73      1137

    accuracy                           0.74      4405
   macro avg       0.61      0.63      0.62      4405
weighted avg       0.72      0.74      0.72      4405



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[   0   11   13   33   24   59]
 [   0  230   75    2    3    2]
 [   0   91  249    1    3    0]
 [   0    1    0 1119  131    3]
 [   0    0    0   98  726  394]
 [   0    0    0    1  210  926]]


#### XGBoost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
modelXGB = XGBClassifier()

modelXGB.fit(X_train,y_train)

y_pred = modelXGB.predict(X_test)

In [ ]:
# Accurracy Score
modelXGB.score(X_test,y_test)

0.7527809307604995

In [ ]:
# Classification Report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00       140
           1       0.66      0.95      0.78       312
           2       0.89      0.60      0.71       344
           3       0.93      0.84      0.89      1254
           4       0.72      0.53      0.61      1218
           5       0.65      0.97      0.78      1137

    accuracy                           0.75      4405
   macro avg       0.64      0.65      0.63      4405
weighted avg       0.75      0.75      0.73      4405



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Confusion Matrix
print(confusion_matrix(y_test,y_pred))

[[   0   13   11   29   21   66]
 [   0  297   15    0    0    0]
 [   0  139  205    0    0    0]
 [   0    0    0 1058  196    0]
 [   0    0    0   45  651  522]
 [   0    0    0    0   32 1105]]


### Test Data and Submission File

In [ ]:
test = pd.read_csv("/content/drive/MyDrive/dataset/test.csv",na_values=['?','-999','Error','xxxxxxxx'])
test_1 = pd.read_csv("/content/drive/MyDrive/dataset/test.csv")

In [ ]:
test.head()

customer_id  ...              feedback
0  fffe43004900440031003700300030003400  ...  Poor Product Quality
1  fffe43004900440031003900370037003300  ...          Poor Website
2  fffe43004900440034003800360037003000  ...   No reason specified
3  fffe43004900440036003200370033003400  ...          Too many ads
4  fffe43004900440035003000370031003900  ...          Poor Website

[5 rows x 24 columns]

In [ ]:
test = test.drop(["customer_id","Name","security_no","referral_id","last_visit_time"],axis=1)

In [ ]:
test.head()

age gender  ...          complaint_status              feedback
0   50      F  ...            Not Applicable  Poor Product Quality
1   41      M  ...            Not Applicable          Poor Website
2   31      F  ...       Solved in Follow-up   No reason specified
3   64      M  ...  No Information Available          Too many ads
4   16      F  ...       Solved in Follow-up          Poor Website

[5 rows x 19 columns]

#### Encoded Some values in training set so doing same in test set

In [ ]:
 for i in test.columns:
   if test[i].dtype=='float64':
     test[i]=test[i].fillna(test[i].mean())
   else:
     test[i]=test[i].fillna(method='ffill')

In [ ]:
test["region_category"] = test.region_category.apply(str)

In [ ]:
test["joined_through_referral"] = test.joined_through_referral.apply(str)

In [ ]:
test["gender"] = le.fit_transform(test.gender)
test["region_category"] = le.fit_transform(test["region_category"])
test["membership_category"] = le.fit_transform(test.membership_category)
test["joined_through_referral"] = le.fit_transform(test["joined_through_referral"])
test["preferred_offer_types"] = le.fit_transform(test["preferred_offer_types"])
test["medium_of_operation"] = le.fit_transform(test["medium_of_operation"])
test["internet_option"] = le.fit_transform(test["internet_option"])
test["used_special_discount"] = le.fit_transform(test["used_special_discount"])
test["offer_application_preference"] = le.fit_transform(test["offer_application_preference"])
test["past_complaint"] = le.fit_transform(test["past_complaint"])
test["complaint_status"] = le.fit_transform(test["complaint_status"])
test["feedback"] = le.fit_transform(test["feedback"])

In [ ]:
test["joining_date"] = test["joining_date"].replace("-",'',regex=True).astype(int)

In [ ]:
result = modelRF.predict(test)

In [ ]:
# result

In [ ]:
submission = pd.DataFrame({
   'customer_id': test_1['customer_id'],
   'churn_risk_score': result,
})

In [ ]:
submission.to_csv('/content/drive/MyDrive/dataset/randomforestresults.csv', index=False)